<?php

/**
 * @file
 * Short description.
 */

use Drupal\node\NodeInterface;

/**
 * Implements hook_mail().
 */
function demo_mail($key, &$message, $params) {
  switch ($key) {
    case 'node_creation_email':
      $node = $params['node'];
      $config = \Drupal::config('custom_mailer.settings');

      $subject = \Drupal::token()
        ->replace($config->get('subject'), ['node' => $node]);

      $body = \Drupal::token()
        ->replace($config->get('message'), ['node' => $node]);

      $message['subject'] = $subject;
      $message['body'][] = $body;

      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function demo_node_insert(NodeInterface $node) {
  $params = ['node' => $node];
  $to = $node->getOwner()->getEmail();
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $result = \Drupal::service('plugin.manager.mail')
    ->mail('demo', 'node_creation_email', $to, $language, $params);

  if ($result['result'] !== TRUE) {
    \Drupal::logger('demo')->error('Unable to send email on node creation: @error', ['@error' => $result['message']]);
    \Drupal::messenger()->addError(t('Unable to send email: @error', ['@error' => $result['message']]));
  }
  else {
    \Drupal::messenger()->addStatus(t('Email sent successfully.'));
  }
}

/**
 * Implements hook_mail_alter().
 */
function demo_mail_alter(&$message) {

  if ($message['key'] == 'node_creation_email') {

    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; ';

  }
}
