# Schema for the configuration files of the moduletask module.
moduletask.settings:
  type: config_object
  label: 'moduletask settings'
  mapping:
    example:
      type: string
      label: 'Example'
