# Schema for the configuration files of the demo module.
demo.settings:
  type: config_object
  label: 'demo settings'
  mapping:
    example:
      type: string
      label: 'Example'

# File.

custom_mailer.settings:
  type: config_object
  label: 'Custom Mailer Settings'
  mapping:
    subject:
      type: string
      label: 'Email Subject'
    message:
      type: string
      label: 'Email Message'

